// <auto-generated />
using System;
using EducationCrm.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EducationCrm.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701060830_AddLeadPayments")]
    partial class AddLeadPayments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EducationCrm.Api.Models.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LeadId");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.ToTable("activities", (string)null);
                });

            modelBuilder.Entity("EducationCrm.Api.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            BranchId = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "rahul@demo-academy.test",
                            FailedLoginAttempts = 0,
                            FullName = "Rahul Sharma",
                            IsActive = true,
                            PasswordHash = "v1.100000.Mt8GC3coU3xegrVi+C2aAw==.i10uchOOE1k5pG2zdL/PW+FxQ7wZ9yM+MW/hwgowbPM=",
                            Role = "Owner",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            BranchId = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "verma@demo-academy.test",
                            FailedLoginAttempts = 0,
                            FullName = "S. Verma",
                            IsActive = true,
                            PasswordHash = "v1.100000.Mt8GC3coU3xegrVi+C2aAw==.i10uchOOE1k5pG2zdL/PW+FxQ7wZ9yM+MW/hwgowbPM=",
                            Role = "Counselor",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            BranchId = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "khanna@demo-academy.test",
                            FailedLoginAttempts = 0,
                            FullName = "R. Khanna",
                            IsActive = true,
                            PasswordHash = "v1.100000.Mt8GC3coU3xegrVi+C2aAw==.i10uchOOE1k5pG2zdL/PW+FxQ7wZ9yM+MW/hwgowbPM=",
                            Role = "ReadOnly",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("EducationCrm.Api.Models.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("branches", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            City = "New Delhi",
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Main Branch",
                            NormalizedName = "MAIN BRANCH",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        });
                });

            modelBuilder.Entity("EducationCrm.Api.Models.CommunicationTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("TenantId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("TenantId", "IsActive", "Channel");

                    b.ToTable("communication_templates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000001"),
                            Body = "Hi {{studentName}}, thank you for your interest in {{course}} at {{tenantName}}. Our counsellor will help you with the next steps. Reply here or call us for any questions.",
                            Category = "Initial Follow-up",
                            Channel = "WhatsApp",
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Initial inquiry WhatsApp",
                            NormalizedName = "INITIAL INQUIRY WHATSAPP",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000002"),
                            Body = "Hi {{studentName}}, this is a reminder for your {{course}} demo. Please keep your questions ready. Your counsellor: {{counsellor}}.",
                            Category = "Demo Reminder",
                            Channel = "WhatsApp",
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Demo reminder",
                            NormalizedName = "DEMO REMINDER",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000003"),
                            Body = "Dear {{studentName}}, we are following up on your {{course}} admission application. Current stage: {{stage}}. Please share any pending details so we can proceed.",
                            Category = "Application Follow-up",
                            Channel = "Email",
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Application follow-up email",
                            NormalizedName = "APPLICATION FOLLOW-UP EMAIL",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000004"),
                            Body = "Hi {{studentName}}, please share the pending documents for your {{course}} admission process. Lead ID: {{leadNumber}}.",
                            Category = "Document Reminder",
                            Channel = "WhatsApp",
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Document reminder",
                            NormalizedName = "DOCUMENT REMINDER",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        });
                });

            modelBuilder.Entity("EducationCrm.Api.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("courses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "MBA Global",
                            NormalizedName = "MBA GLOBAL",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Data Science",
                            NormalizedName = "DATA SCIENCE",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "UI/UX Design",
                            NormalizedName = "UI/UX DESIGN",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Full Stack Dev",
                            NormalizedName = "FULL STACK DEV",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Digital Marketing",
                            NormalizedName = "DIGITAL MARKETING",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        });
                });

            modelBuilder.Entity("EducationCrm.Api.Models.DocumentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("TenantId", "SortOrder")
                        .IsUnique();

                    b.ToTable("document_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsRequired = true,
                            Name = "ID Proof",
                            NormalizedName = "ID PROOF",
                            SortOrder = 10,
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsRequired = true,
                            Name = "Address Proof",
                            NormalizedName = "ADDRESS PROOF",
                            SortOrder = 20,
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsRequired = true,
                            Name = "Academic Marksheet",
                            NormalizedName = "ACADEMIC MARKSHEET",
                            SortOrder = 30,
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsRequired = true,
                            Name = "Admission Form",
                            NormalizedName = "ADMISSION FORM",
                            SortOrder = 40,
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsRequired = false,
                            Name = "Payment Receipt",
                            NormalizedName = "PAYMENT RECEIPT",
                            SortOrder = 50,
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        });
                });

            modelBuilder.Entity("EducationCrm.Api.Models.FollowUp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("LeadId");

                    b.HasIndex("TenantId", "DueAt");

                    b.HasIndex("TenantId", "Status", "DueAt");

                    b.ToTable("follow_ups", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000001"),
                            AssignedUserId = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            DueAt = new DateTime(2026, 6, 25, 6, 15, 0, 0, DateTimeKind.Unspecified),
                            LeadId = new Guid("70000000-0000-0000-0000-000000000001"),
                            Priority = "High",
                            Status = "Scheduled",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Type = "Call",
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000002"),
                            AssignedUserId = new Guid("30000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            DueAt = new DateTime(2026, 6, 25, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            LeadId = new Guid("70000000-0000-0000-0000-000000000002"),
                            Priority = "Medium",
                            Status = "Scheduled",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Type = "WhatsApp",
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000003"),
                            AssignedUserId = new Guid("30000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            DueAt = new DateTime(2026, 6, 25, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            LeadId = new Guid("70000000-0000-0000-0000-000000000003"),
                            Priority = "Low",
                            Status = "Scheduled",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Type = "Email",
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        });
                });

            modelBuilder.Entity("EducationCrm.Api.Models.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ArchivedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("GuardianName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("LeadNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("LeadSourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeadStageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("NextFollowUpAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NormalizedPhone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedByUserId");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CourseId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LeadSourceId");

                    b.HasIndex("LeadStageId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("TenantId", "ArchivedAt");

                    b.HasIndex("TenantId", "AssignedUserId");

                    b.HasIndex("TenantId", "BranchId");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.HasIndex("TenantId", "LeadNumber")
                        .IsUnique();

                    b.HasIndex("TenantId", "LeadStageId");

                    b.HasIndex("TenantId", "NormalizedPhone")
                        .IsUnique();

                    b.ToTable("leads", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000001"),
                            AssignedUserId = new Guid("30000000-0000-0000-0000-000000000002"),
                            BranchId = new Guid("20000000-0000-0000-0000-000000000001"),
                            CourseId = new Guid("40000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 6, 7, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "arjun.a@email.com",
                            LeadNumber = "LD-1001",
                            LeadSourceId = new Guid("60000000-0000-0000-0000-000000000001"),
                            LeadStageId = new Guid("50000000-0000-0000-0000-000000000006"),
                            NextFollowUpAt = new DateTime(2026, 6, 25, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            NormalizedPhone = "919876543210",
                            Phone = "+91 98765 43210",
                            Priority = "High",
                            Status = "Enrolled",
                            StudentName = "Arjun Adhikari",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 7, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000002"),
                            AssignedUserId = new Guid("30000000-0000-0000-0000-000000000003"),
                            BranchId = new Guid("20000000-0000-0000-0000-000000000001"),
                            CourseId = new Guid("40000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 6, 19, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "priya.s@outlook.com",
                            LeadNumber = "LD-1002",
                            LeadSourceId = new Guid("60000000-0000-0000-0000-000000000002"),
                            LeadStageId = new Guid("50000000-0000-0000-0000-000000000003"),
                            NextFollowUpAt = new DateTime(2026, 6, 26, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            NormalizedPhone = "919123456789",
                            Phone = "+91 91234 56789",
                            Priority = "Medium",
                            Status = "Interested",
                            StudentName = "Priya Sharma",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 19, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000003"),
                            AssignedUserId = new Guid("30000000-0000-0000-0000-000000000001"),
                            BranchId = new Guid("20000000-0000-0000-0000-000000000001"),
                            CourseId = new Guid("40000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 6, 21, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "m.jones@gmail.com",
                            LeadNumber = "LD-1003",
                            LeadSourceId = new Guid("60000000-0000-0000-0000-000000000003"),
                            LeadStageId = new Guid("50000000-0000-0000-0000-000000000004"),
                            NextFollowUpAt = new DateTime(2026, 6, 25, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            NormalizedPhone = "919988776655",
                            Phone = "+91 99887 76655",
                            Priority = "High",
                            Status = "Follow Up",
                            StudentName = "Michael Jones",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 21, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000004"),
                            AssignedUserId = new Guid("30000000-0000-0000-0000-000000000002"),
                            BranchId = new Guid("20000000-0000-0000-0000-000000000001"),
                            CourseId = new Guid("40000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 5, 31, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "d.reddy@tcs.com",
                            LeadNumber = "LD-1004",
                            LeadSourceId = new Guid("60000000-0000-0000-0000-000000000004"),
                            LeadStageId = new Guid("50000000-0000-0000-0000-000000000007"),
                            NormalizedPhone = "919000011223",
                            Phone = "+91 90000 11223",
                            Priority = "Low",
                            Status = "Dropped",
                            StudentName = "Deepak Reddy",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 5, 31, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000005"),
                            AssignedUserId = new Guid("30000000-0000-0000-0000-000000000001"),
                            BranchId = new Guid("20000000-0000-0000-0000-000000000001"),
                            CourseId = new Guid("40000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 6, 24, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "k.luthra@gmail.com",
                            LeadNumber = "LD-1005",
                            LeadSourceId = new Guid("60000000-0000-0000-0000-000000000005"),
                            LeadStageId = new Guid("50000000-0000-0000-0000-000000000001"),
                            NextFollowUpAt = new DateTime(2026, 6, 25, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            NormalizedPhone = "918877665544",
                            Phone = "+91 88776 65544",
                            Priority = "Medium",
                            Status = "New Lead",
                            StudentName = "Kriti Luthra",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 24, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        });
                });

            modelBuilder.Entity("EducationCrm.Api.Models.LeadDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CloudinaryAssetId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("CloudinaryDeliveryType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("CloudinaryPublicId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CloudinaryResourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("CloudinarySecureUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uuid");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("LeadId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("TenantId", "CloudinaryPublicId");

                    b.HasIndex("TenantId", "Status");

                    b.HasIndex("TenantId", "LeadId", "DocumentTypeId")
                        .IsUnique();

                    b.ToTable("lead_documents", (string)null);
                });

            modelBuilder.Entity("EducationCrm.Api.Models.LeadPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountDue")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CancelledByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LeadId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("TenantId", "DueDate");

                    b.HasIndex("TenantId", "LeadId");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("lead_payments", (string)null);
                });

            modelBuilder.Entity("EducationCrm.Api.Models.LeadPaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeadPaymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReceiptNumber")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LeadPaymentId");

                    b.HasIndex("TenantId", "LeadPaymentId");

                    b.HasIndex("TenantId", "ReceiptNumber")
                        .IsUnique()
                        .HasFilter("\"ReceiptNumber\" IS NOT NULL");

                    b.HasIndex("TenantId", "ReferenceNumber");

                    b.ToTable("lead_payment_transactions", (string)null);
                });

            modelBuilder.Entity("EducationCrm.Api.Models.LeadSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("lead_sources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Google Ads",
                            NormalizedName = "GOOGLE ADS",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Website",
                            NormalizedName = "WEBSITE",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "LinkedIn",
                            NormalizedName = "LINKEDIN",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Referral",
                            NormalizedName = "REFERRAL",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Offline Expo",
                            NormalizedName = "OFFLINE EXPO",
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        });
                });

            modelBuilder.Entity("EducationCrm.Api.Models.LeadStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefaultStage")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLostStage")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWonStage")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IsDefaultStage")
                        .IsUnique()
                        .HasFilter("\"IsDefaultStage\" = TRUE AND \"IsActive\" = TRUE");

                    b.HasIndex("TenantId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("TenantId", "SortOrder")
                        .IsUnique();

                    b.ToTable("lead_stages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDefaultStage = true,
                            IsLostStage = false,
                            IsWonStage = false,
                            Name = "New Inquiry",
                            NormalizedName = "NEW INQUIRY",
                            SortOrder = 10,
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDefaultStage = false,
                            IsLostStage = false,
                            IsWonStage = false,
                            Name = "Contacted",
                            NormalizedName = "CONTACTED",
                            SortOrder = 20,
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDefaultStage = false,
                            IsLostStage = false,
                            IsWonStage = false,
                            Name = "Interested",
                            NormalizedName = "INTERESTED",
                            SortOrder = 30,
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDefaultStage = false,
                            IsLostStage = false,
                            IsWonStage = false,
                            Name = "Demo Scheduled",
                            NormalizedName = "DEMO SCHEDULED",
                            SortOrder = 40,
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDefaultStage = false,
                            IsLostStage = false,
                            IsWonStage = false,
                            Name = "Application Started",
                            NormalizedName = "APPLICATION STARTED",
                            SortOrder = 50,
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDefaultStage = false,
                            IsLostStage = false,
                            IsWonStage = true,
                            Name = "Enrolled",
                            NormalizedName = "ENROLLED",
                            SortOrder = 60,
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDefaultStage = false,
                            IsLostStage = true,
                            IsWonStage = false,
                            Name = "Dropped",
                            NormalizedName = "DROPPED",
                            SortOrder = 70,
                            TenantId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            Version = 1
                        });
                });

            modelBuilder.Entity("EducationCrm.Api.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("BrandColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DefaultAssigneeUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DefaultBranchId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("State")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("DefaultAssigneeUserId");

                    b.HasIndex("DefaultBranchId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tenants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            BrandColor = "#2171D3",
                            City = "New Delhi",
                            ContactEmail = "admissions@demo-academy.test",
                            ContactPhone = "+91 11 4000 0000",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 6, 25, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            DefaultAssigneeUserId = new Guid("30000000-0000-0000-0000-000000000002"),
                            DefaultBranchId = new Guid("20000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Name = "Demo Academy",
                            Slug = "demo-academy",
                            State = "Delhi",
                            TimeZone = "Asia/Kolkata",
                            Version = 1
                        });
                });

            modelBuilder.Entity("EducationCrm.Api.Models.Activity", b =>
                {
                    b.HasOne("EducationCrm.Api.Models.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EducationCrm.Api.Models.Lead", "Lead")
                        .WithMany("Activities")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationCrm.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Lead");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EducationCrm.Api.Models.AppUser", b =>
                {
                    b.HasOne("EducationCrm.Api.Models.Branch", "Branch")
                        .WithMany("Users")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EducationCrm.Api.Models.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EducationCrm.Api.Models.Branch", b =>
                {
                    b.HasOne("EducationCrm.Api.Models.Tenant", "Tenant")
                        .WithMany("Branches")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EducationCrm.Api.Models.CommunicationTemplate", b =>
                {
                    b.HasOne("EducationCrm.Api.Models.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EducationCrm.Api.Models.Tenant", "Tenant")
                        .WithMany("CommunicationTemplates")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducationCrm.Api.Models.AppUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Tenant");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("EducationCrm.Api.Models.Course", b =>
                {
                    b.HasOne("EducationCrm.Api.Models.Tenant", "Tenant")
                        .WithMany("Courses")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EducationCrm.Api.Models.DocumentType", b =>
                {
                    b.HasOne("EducationCrm.Api.Models.Tenant", "Tenant")
                        .WithMany("DocumentTypes")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EducationCrm.Api.Models.FollowUp", b =>
                {
                    b.HasOne("EducationCrm.Api.Models.AppUser", "AssignedUser")
                        .WithMany("AssignedFollowUps")
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EducationCrm.Api.Models.Lead", "Lead")
                        .WithMany("FollowUps")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationCrm.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("Lead");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EducationCrm.Api.Models.Lead", b =>
                {
                    b.HasOne("EducationCrm.Api.Models.AppUser", "ArchivedByUser")
                        .WithMany()
                        .HasForeignKey("ArchivedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EducationCrm.Api.Models.AppUser", "AssignedUser")
                        .WithMany("AssignedLeads")
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EducationCrm.Api.Models.Branch", "Branch")
                        .WithMany("Leads")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EducationCrm.Api.Models.Course", "Course")
                        .WithMany("Leads")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducationCrm.Api.Models.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EducationCrm.Api.Models.LeadSource", "LeadSource")
                        .WithMany("Leads")
                        .HasForeignKey("LeadSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducationCrm.Api.Models.LeadStage", "LeadStage")
                        .WithMany("Leads")
                        .HasForeignKey("LeadStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducationCrm.Api.Models.Tenant", "Tenant")
                        .WithMany("Leads")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducationCrm.Api.Models.AppUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ArchivedByUser");

                    b.Navigation("AssignedUser");

                    b.Navigation("Branch");

                    b.Navigation("Course");

                    b.Navigation("CreatedByUser");

                    b.Navigation("LeadSource");

                    b.Navigation("LeadStage");

                    b.Navigation("Tenant");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("EducationCrm.Api.Models.LeadDocument", b =>
                {
                    b.HasOne("EducationCrm.Api.Models.DocumentType", "DocumentType")
                        .WithMany("LeadDocuments")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducationCrm.Api.Models.Lead", "Lead")
                        .WithMany("Documents")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationCrm.Api.Models.AppUser", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EducationCrm.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducationCrm.Api.Models.AppUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EducationCrm.Api.Models.AppUser", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DocumentType");

                    b.Navigation("Lead");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("Tenant");

                    b.Navigation("UpdatedByUser");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("EducationCrm.Api.Models.LeadPayment", b =>
                {
                    b.HasOne("EducationCrm.Api.Models.AppUser", "CancelledByUser")
                        .WithMany()
                        .HasForeignKey("CancelledByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EducationCrm.Api.Models.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EducationCrm.Api.Models.Lead", "Lead")
                        .WithMany("Payments")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationCrm.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EducationCrm.Api.Models.AppUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CancelledByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Lead");

                    b.Navigation("Tenant");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("EducationCrm.Api.Models.LeadPaymentTransaction", b =>
                {
                    b.HasOne("EducationCrm.Api.Models.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EducationCrm.Api.Models.LeadPayment", "LeadPayment")
                        .WithMany("Transactions")
                        .HasForeignKey("LeadPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationCrm.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("LeadPayment");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EducationCrm.Api.Models.LeadSource", b =>
                {
                    b.HasOne("EducationCrm.Api.Models.Tenant", "Tenant")
                        .WithMany("LeadSources")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EducationCrm.Api.Models.LeadStage", b =>
                {
                    b.HasOne("EducationCrm.Api.Models.Tenant", "Tenant")
                        .WithMany("LeadStages")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EducationCrm.Api.Models.Tenant", b =>
                {
                    b.HasOne("EducationCrm.Api.Models.AppUser", "DefaultAssigneeUser")
                        .WithMany()
                        .HasForeignKey("DefaultAssigneeUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EducationCrm.Api.Models.Branch", "DefaultBranch")
                        .WithMany()
                        .HasForeignKey("DefaultBranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DefaultAssigneeUser");

                    b.Navigation("DefaultBranch");
                });

            modelBuilder.Entity("EducationCrm.Api.Models.AppUser", b =>
                {
                    b.Navigation("AssignedFollowUps");

                    b.Navigation("AssignedLeads");
                });

            modelBuilder.Entity("EducationCrm.Api.Models.Branch", b =>
                {
                    b.Navigation("Leads");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EducationCrm.Api.Models.Course", b =>
                {
                    b.Navigation("Leads");
                });

            modelBuilder.Entity("EducationCrm.Api.Models.DocumentType", b =>
                {
                    b.Navigation("LeadDocuments");
                });

            modelBuilder.Entity("EducationCrm.Api.Models.Lead", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Documents");

                    b.Navigation("FollowUps");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("EducationCrm.Api.Models.LeadPayment", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("EducationCrm.Api.Models.LeadSource", b =>
                {
                    b.Navigation("Leads");
                });

            modelBuilder.Entity("EducationCrm.Api.Models.LeadStage", b =>
                {
                    b.Navigation("Leads");
                });

            modelBuilder.Entity("EducationCrm.Api.Models.Tenant", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("CommunicationTemplates");

                    b.Navigation("Courses");

                    b.Navigation("DocumentTypes");

                    b.Navigation("LeadSources");

                    b.Navigation("LeadStages");

                    b.Navigation("Leads");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
